apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "kube-endpoints-controller.fullname" . }}
  labels:
    {{- include "kube-endpoints-controller.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - kopf.dev
    resources:
    - clusterkopfpeerings
    verbs: 
    - list
    - watch
    - patch
    - get
  - apiGroups: 
    - apiextensions.k8s.io
    resources: 
    - customresourcedefinitions
    verbs: 
    - list
    - watch
  
  # for kube-endpoints-controller
  - apiGroups: 
    - ""
    resources: 
    - namespaces
    verbs: 
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - endpoints
    - services
    verbs:
    - get
    - list
    - watch