apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-endpoints-controller.fullname" . }}
  labels:
    {{- include "kube-endpoints-controller.labels" . | nindent 4 }}
data:
  cfg.yaml: |
    {{- .Values.cfg | toYaml | nindent 4 }} 
